# Generated by Django 3.2.18 on 2023-04-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
