# Generated by Django 3.2.18 on 2023-04-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_partner', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commission_traesu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commission_motorist', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_payed', models.BooleanField(default=False)),
                ('id_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.billing')),
            ],
        ),
    ]
